name: epios
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_svg: ^0.19.0
  font_awesome_flutter: ^8.8.1
  qrscan: ^0.2.17
  eosdart: ^0.4.6
  shared_preferences: ^0.5.10
  encrypt: ^4.0.3
  base32: 1.1.1
  crypto: ^2.1.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.15.4
  flutter_launcher_icons: "^0.7.3" 

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:

  uses-material-design: true

  assets: 
    - assets/images/svgs/epios_logo.svg
    - assets/images/svgs/virus.svg
    - assets/images/svgs/map.svg
    - assets/images/svgs/user.svg
    - assets/images/svgs/mail.svg
    - assets/images/svgs/scanqr.svg
    - assets/images/svgs/test.svg
    - assets/images/svgs/test_pending.svg
    - assets/images/svgs/test_positive.svg
    - assets/images/svgs/test_negative.svg

  fonts:
    - family: helvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttf
        - asset: assets/fonts/Helvetica-Bold.ttf
          weight: 700

